export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_KOTOS_PENDING = 'REQUEST_KOTOS_PENDING';
export const REQUEST_KOTOS_SUCCESS = 'REQUEST_KOTOS_SUCCESS';
export const REQUEST_KOTOS_FAILED = 'REQUEST_KOTOS_FAILED';
